name: DastScan

on: [push]

jobs:
  dast_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull, build and run PyGoat
        run: |
          docker pull pygoat/pygoat:latest
          docker run --rm -d -p 8000:8000 pygoat/pygoat:latest

      - name: Wait for PyGoat to be ready
        run: |
          sleep 20 # Wait for the application to start

      - name: Install ZAP Docker
        run: |
          docker pull ghcr.io/zaproxy/zaproxy:stable

      - name: Create Report Directory
        run: |
          mkdir -p $GITHUB_WORKSPACE/zap/wrk

      - name: Run Dynamic Application Security Testing with ZAP
        run: |
          echo "biba" > $GITHUB_WORKSPACE/zap/wrk/test.md
          ls
          docker run -u zap -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable zap.sh -cmd -host 127.0.0.1 -port 8000 -quickurl http://127.0.0.1:8000 -quickout /zap/wrk/zap_report.html -quickprogress
          echo "DAST Report generated at /zap/wrk/zap_report.html"

      - name: Commit file
        run: |
          git config --local user.email "dinaraparanid@gmail.com"
          git config --local user.name "dinaraparanid"
          git add zap/wrk/zap_report.html
          git commit -m "Add report" || echo "No changes to commit"
          git push
