name: DastScan

on: [push]

jobs:
  dast_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull, build and run PyGoat
        run: |
          docker pull pygoat/pygoat:latest
          docker run --rm -d -p 8000:8000 pygoat/pygoat:latest

      - name: Wait for PyGoat to be ready
        run: |
          sleep 20 # Wait for the application to start

      - name: Run Dynamic Application Security Testing with ZAP
        uses: zaproxy/action-baseline@v0.13.0
        with:
          target: http://127.0.0.1:8000
          cmd_options: '-r report_html.html'
          allow_issue_writing: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: |
            report_html.html
